### PR TITLE
ENH: Add save capability to surface plot

### LINKED ISSUE #19: ENH: Capability to download images
Add the ability to download the images.

- Probably a separate download icon for surface and altitude to save them separately.
- Can we remove elements when downloading? i.e. we probably wouldn't want the altitude box or surface line in a saved image.
- Can we add metadata to the save image? It would be nice to put in the Date, F10.7, ap, species, altitude, and location so that someone knew exactly what they made.

### PR DESCRIPTION
**Pull request by greglucas**
Closes #19

Adding a "download" button next to the variables in the plot. When it is clicked a Blob is created from the d3 svg and pops up a download dialog box.

### CODE REVIEW

**Comment by jennyknuth** [comment]
I think there is a way to add a header, but I pretty much just copied your code for the actual download part. That was something I'd have to figure out…

I think now the altitude plot is not in the image. But we could add a button to that plot and download it as well, with the same function. We'd just pass in the id/ViewChild of the svg we want to download.

**Comment by greglucas** [comment]
Sounds good, I think we should leave the header/metadata piece until later.

I was removing the "altitude box", the red outline on the surface plot because I found it distracting (not the altitude line plots off to the side). But, this looks like it keeps it around?

**Comment by jennyknuth** [comment]
oh, THAT altitude box, I didn't grasp that, yeah sure, we can remove that!

**Comment by jennyknuth** [comment]
Hang on, let me see how to do that now…

**Comment by greglucas** [comment]
That can be a follow-up as well. We don't have to put everything into the one PR. Small follow-ons can be easier to implement too.

**Comment by jennyknuth** [comment]
Okay, good news, I was able to both hide the altitude box and the tooltip (tooltip now disappears when cursor leaves the map). I think I found a pretty simple way to do both of those things.

**Comment by greglucas** [comment]
@jennyknuth do you want to rebase this one and keep the commits you want?

**Review by jennyknuth — APPROVED** [review]

**Pull request merged**
